document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\'en\'>");
document.writeln("<head>");
document.writeln("    <meta charset=\'UTF-8\'>");
document.writeln("    <meta name=\'viewport\' content=\'width=device-width, initial-scale=1.0\'>");
document.writeln("    <meta http-equiv=\'X-UA-Compatible\' content=\'ie=edge\'>");
document.writeln("    <title>Document</title>");
document.writeln("    <link rel=\'stylesheet\' href=\'../css/base.css\'>");
document.writeln("    <link rel=\'stylesheet\' href=\'../css/jumei.css\'>");
document.writeln("    <script src=\'../js/jquery-3.4.1.js\'></script>");
document.writeln("    <script src=\'../js/cebianlan.js\'></script>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("        <div class=\'ibar_main_panel\'>");
document.writeln("                <ul class=\'ibar_mp_center\'>");
document.writeln("                    <li class=\'mpbtn_login\'><a href=\'\'><s></s>登录</a></li>");
document.writeln("                    <li class=\'mpbtn_cart\'><a href=\'#\' data-plugin=\'iBarCart\'><s></s><span class=\'text\'>购物车</span><span");
document.writeln("                                class=\'cart_num\'>0</span></a></li>");
document.writeln("                    <li class=\'mpbtn_asset\'><a href=\'#\' data-judgelogin=\'1\' data-plugin=\'iBarAsset\'><s></s>我的财产</a>");
document.writeln("                        <div class=\'mp_tooltip\' style=\'display: none;\'>我的财产<s class=\'icon_arrow_right_black\'></s></div>");
document.writeln("                    </li>");
document.writeln("                    <li class=\'mpbtn_favorite\'><a href=\'#\' data-judgelogin=\'1\' data-plugin=\'iBarFavorite\'><s></s>我的心愿单</a>");
document.writeln("                        <div class=\'mp_tooltip\' style=\'display: none;\'>我的心愿单<s class=\'icon_arrow_right_black\'></s></div>");
document.writeln("                    </li>");
document.writeln("                    <li class=\'mpbtn_histroy\'><a href=\'#\' data-plugin=\'iBarHistroy\'><s></s>我看过的</a>");
document.writeln("                        <div class=\'mp_tooltip\' style=\'display: none;\'>我看过的<s class=\'icon_arrow_right_black\'></s></div>");
document.writeln("                    </li>");
document.writeln("                </ul>");
document.writeln("                <ul class=\'ibar_mp_bottom\'>");
document.writeln("                    <li class=\'mpbtn_qrcode\'><a href=\'#\'><s></s>手机聚美</a>");
document.writeln("                        <div class=\'mp_qrcode\' style=\'display: none;\'><img src=\'../img/erweima.png\'");
document.writeln("                                data-lazysrc=\'http://s0.jmstatic.com/templates/jumei/images/ibar/qrcode.png?v=0\' width=\'148\'");
document.writeln("                                height=\'175\'><s class=\'icon_arrow_white\'></s></div>");
document.writeln("                    </li>");
document.writeln("                    <li class=\'mpbtn_support\'><a href=\'#\' data-plugin=\'iBarFaq\'><s></s>客服中心</a>");
document.writeln("                        <div class=\'mp_tooltip\' style=\'display: none;\'>客服中心<s class=\'icon_arrow_right_black\'></s></div>");
document.writeln("                    </li>");
document.writeln("                    <li class=\'mpbtn_gotop\' id=\'gotop\'><a href=\'#\' class=\'btn_gotop\'><s></s>返回顶部</a>");
document.writeln("                        <div class=\'mp_tooltip\' style=\'display: none;\'>返回顶部<s class=\'icon_arrow_right_black\'></s></div>");
document.writeln("                    </li>");
document.writeln("                </ul>");
document.writeln("            </div>");
document.writeln("</body>");
document.writeln("</html>");