document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\'en\'>");
document.writeln("");
document.writeln("<head>");
document.writeln("    <meta charset=\'UTF-8\'>");
document.writeln("    <meta name=\'viewport\' content=\'width=device-width, initial-scale=1.0\'>");
document.writeln("    <meta http-equiv=\'X-UA-Compatible\' content=\'ie=edge\'>");
document.writeln("    <title>Document</title>");
document.writeln("    <link rel=\'stylesheet\' href=\'../css/base.css\'>");
document.writeln("    <link rel=\'stylesheet\' href=\'../css/jumei.css\'>");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("    <div id=\'footer\' class=\'footer\'>");
document.writeln("        <div id=\'footer_textarea\'>");
document.writeln("            <div class=\'footer_top\'>");
document.writeln("                <div class=\'footer_con footer_credit\' id=\'footer_credit\'>");
document.writeln("                    <a href=\'\' class=\'foot_link mostmall\' target=\'_blank\' rel=\'nofollow\'>");
document.writeln("                        <span class=\'first corn\'></span><span class=\'con\'><b>值得信赖美妆电商</b></span>四千万用户信赖");
document.writeln("                    </a>");
document.writeln("                    <a href=\'\' class=\'foot_link quality\' target=\'_blank\' rel=\'nofollow\'>");
document.writeln("                        <span class=\'corn\'></span><span class=\'con\'><b>成功在美上市</b></span>股票代码NYSE:JMEI");
document.writeln("                    </a>");
document.writeln("                    <a href=\'\' class=\'foot_link back\' rel=\'nofollow\' target=\'_blank\'>");
document.writeln("                        <span class=\'corn\'></span><span class=\'con\'><b>品牌防伪码</b></span>支持品牌官网验真");
document.writeln("                    </a>");
document.writeln("                   ");
document.writeln("                    <a href=\'\' class=\'foot_link consignment\' target=\'_blank\' rel=\'nofollow\'>");
document.writeln("                        <span class=\'corn\'></span><span class=\'con\'><b>百万用户口碑</b></span>帮你只选对的,不选贵的");
document.writeln("                    </a>");
document.writeln("                    <a href=\'\' class=\'foot_link packaging\' target=\'_blank\' rel=\'nofollow\'>");
document.writeln("                        <span class=\'corn\'></span><span class=\'con\'><b>订单闪电发货</b></span>1.5小时订单急速出库");
document.writeln("                    </a>");
document.writeln("                    <a href=\'\' class=\'foot_link confide\' target=\'_blank\' rel=\'nofollow\'>");
document.writeln("                        <span class=\'corn\'></span><span class=\'con\'><b>大牌明星热荐</b></span>打造精致明星脸");
document.writeln("                    </a>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("            <div class=\'footer_top_sen\'>");
document.writeln("                <div class=\'footer_con footer_links\' id=\'footer_links\'>");
document.writeln("                    <ul class=\'linksa\'>");
document.writeln("                        <li class=\'links\'>服务保障</li>");
document.writeln("                        <li><a href=\'\' target=\'_blank\' rel=\'nofollow\'>品牌真品防伪码</a></li>");
document.writeln("                        <li><a href=\'\' target=\'_blank\' rel=\'nofollow\'>正品保证</a></li>");
document.writeln("                        <li><a href=\'\' target=\'_blank\' rel=\'nofollow\'>专属客服服务</a></li>");
document.writeln("                        <li><span class=\'footer_zcemail\'>总裁邮箱ceo@jumei.com</span></li>");
document.writeln("                    </ul>");
document.writeln("                    <ul class=\'linksb\'>");
document.writeln("                        <li class=\'links\'>使用帮助</li>");
document.writeln("                        <li><a href=\'\' target=\'_blank\' rel=\'nofollow\'>新手指南</a></li>");
document.writeln("                        <li><a href=\'\' target=\'_blank\' rel=\'nofollow\'>常见问题</a></li>");
document.writeln("                        <li><a href=\'\' target=\'_blank\' rel=\'nofollow\'>帮助中心</a></li>");
document.writeln("                        <li><a href=\'\' target=\'_blank\' rel=\'nofollow\'>用户协议</a>");
document.writeln("                        </li>");
document.writeln("                        <li><a href=\'\' target=\'_blank\' rel=\'nofollow\'>公示制度</a></li>");
document.writeln("                        <li><a href=\'\' target=\'_blank\' rel=\'nofollow\'>聚美隐私权政策</a></li>");
document.writeln("                        <li><a href=\'\' target=\'_blank\' rel=\'nofollow\'>个人信息管理规则</a></li>");
document.writeln("                        <li><a href=\'\' target=\'_blank\' rel=\'nofollow\'>意见反馈及投诉举报规则</a>");
document.writeln("                        </li>");
document.writeln("                        <li><a href=\'\' target=\'_blank\' rel=\'nofollow\'>知识产权维权处理规则</a></li>");
document.writeln("                        <li><a href=\'\' target=\'_blank\' rel=\'nofollow\'>评价管理规则</a></li>");
document.writeln("                    </ul>");
document.writeln("                    <ul class=\'linksc\'>");
document.writeln("                        <li class=\'links\'>支付方式</li>");
document.writeln("                        <li><a href=\'\' target=\'_blank\' rel=\'nofollow\'>货到付款</a></li>");
document.writeln("                        <li><a href=\'\' target=\'_blank\' rel=\'nofollow\'>在线支付</a></li>");
document.writeln("                        <li><a href=\'\' target=\'_blank\' rel=\'nofollow\'>余额支付</a></li>");
document.writeln("                        <li><a href=\'\' target=\'_blank\' rel=\'nofollow\'>现金券支付</a></li>");
document.writeln("                    </ul>");
document.writeln("");
document.writeln("                    <ul class=\'linksd\'>");
document.writeln("                        <li class=\'links\'>配送方式</li>");
document.writeln("                        <li><a href=\'\' target=\'_blank\' rel=\'nofollow\'>包邮政策</a></li>");
document.writeln("                        <li><a href=\'\' target=\'_blank\' rel=\'nofollow\'>配送说明</a></li>");
document.writeln("                        <li><a href=\'\' target=\'_blank\' rel=\'nofollow\'>运费说明</a></li>");
document.writeln("                        <li><a href=\'\' target=\'_blank\' rel=\'nofollow\'>验货签收</a></li>");
document.writeln("                    </ul>");
document.writeln("");
document.writeln("                    <ul class=\'linkse\'>");
document.writeln("                        <li class=\'links\'>售后服务</li>");
document.writeln("                        <li><a href=\'\' target=\'_blank\' rel=\'nofollow\'>正品承诺</a></li>");
document.writeln("                        <li><a href=\'\' target=\'_blank\' rel=\'nofollow\'>售后咨询</a>");
document.writeln("                        </li>");
document.writeln("                        <li><a href=\'\' target=\'_blank\' rel=\'nofollow\'>退货政策</a>");
document.writeln("                        </li>");
document.writeln("                        <li><a href=\'\' target=\'_blank\' rel=\'nofollow\'>退货办理</a>");
document.writeln("                        </li>");
document.writeln("                    </ul>");
document.writeln("                    <div class=\'links_er_box\'>");
document.writeln("                        <ul class=\'linksf\'>");
document.writeln("                            <li class=\'links\'>手机聚美</li>");
document.writeln("                            <li><span class=\'link_bottom_pic\'></span></li>");
document.writeln("                            <li>下载移动客户端</li>");
document.writeln("                        </ul>");
document.writeln("                        <ul class=\'linksg\'>");
document.writeln("                            <li class=\'links\'>聚美微信</li>");
document.writeln("                            <li><span class=\'link_bottom_pic\'></span></li>");
document.writeln("                            <li>聚美官方微信</li>");
document.writeln("                        </ul>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("");
document.writeln("            <div class=\'footer_dy\' id=\'footer_dy\'>");
document.writeln("                <div class=\'play_box\'><span class=\'play\'></span></div>");
document.writeln("            </div>");
document.writeln("            <div class=\'footer_center\'>");
document.writeln("                <div class=\'footer_con\' id=\'footer_link\'>");
document.writeln("                    <a href=\'\' target=\'_blank\' rel=\'nofollow\'>关于聚美优品</a>");
document.writeln("                    <a href=\'\' target=\'_blank\' rel=\'nofollow\'>INVESTOR RELATIONS</a>");
document.writeln("                    <a href=\'\' target=\'_blank\' rel=\'nofollow\'>合作招商</a>");
document.writeln("                    <a href=\'\' target=\'_blank\' rel=\'nofollow\'>获取更新</a>");
document.writeln("                    <a href=\'\' target=\'_blank\' rel=\'nofollow\'>加入聚美</a>");
document.writeln("                    <a href=\'\' target=\'_blank\' rel=\'nofollow\'>品牌合作专区</a>");
document.writeln("                    <!-- <a href=\'http://cps.jumei.com?from=footer\' target=\'_blank\' rel=\'nofollow\'>网站联盟</a> -->");
document.writeln("                    <a href=\'\' target=\'_blank\' rel=\'nofollow\'>媒体报道</a>");
document.writeln("                    <a href=\'\' target=\'_blank\' rel=\'nofollow\'>商务合作</a>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("            <div id=\'footer_copyright\' class=\'footer_copyright\'>");
document.writeln("                <div class=\'footer_con\'>");
document.writeln("                    <p class=\'footer_copy_con\'>");
document.writeln("                        COPYRIGHT © 2010-2019 北京创锐文化传媒有限公司 JUMEI.COM 保留一切权利。");
document.writeln("                        客服热线：400-123-8888");
document.writeln("                        <br>");
document.writeln("                        京公网安备 11010102001226 | <a href=\'\' target=\'_blank\' rel=\'nofollow\'>京ICP证111033号</a>");
document.writeln("                        | <a href=\'\'>食品经营许可证</a>");
document.writeln("                        | <a href=\'\' target=\'_blank\' rel=\'nofollow\'>营业执照</a>");
document.writeln("                        | <a href=\'\' target=\'_blank\' rel=\'nofollow\'>ICP许可证</a>");
document.writeln("                        | <a href=\'\' target=\'_blank\' rel=\'nofollow\'>出版物经营许可证</a>");
document.writeln("                        | <a href=\'\' target=\'_blank\' rel=\'nofollow\'>第二类医疗器械经营备案凭证</a>");
document.writeln("                        | <a href=\'\' target=\'_blank\' rel=\'nofollow\'>网络食品交易第三方平台提供者备案信息表</a>");
document.writeln("                        | <a href=\'\' target=\'_blank\' rel=\'nofollow\'>增值电信业务经营许可证</a>");
document.writeln("                    </p>");
document.writeln("                    <p>");
document.writeln("                        <a href=\'javascript:void(0)\' class=\'footer_copy_logo logo01\' rel=\'nofollow\'></a>");
document.writeln("                        <a href=\'\' target=\'_blank\' class=\'footer_copy_logo logo02\' rel=\'nofollow\'></a>");
document.writeln("                        <a href=\'\' class=\'footer_copy_logo logo03\' rel=\'nofollow\'></a>");
document.writeln("                        <a href=\'\' class=\'footer_copy_logo logo04\' rel=\'nofollow\'></a>");
document.writeln("                        <a href=\'\' target=\'_blank\' class=\'footer_copy_logo logo05\' rel=\'nofollow\'></a>");
document.writeln("                        <a href=\'\' class=\'footer_logo6\' rel=\'nofollow\'></a>");
document.writeln("                    </p>");
document.writeln("                  ");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</body>");
document.writeln("");
document.writeln("</html>");